### ISSUE TITLE
Delete images from recents?

### ISSUE THREAD

**Issue by webframp** [alcor/stickerclip#4]
Awesome app, was curious if there's a way to delete an image from recents?

**Comment by macjustice** [comment]
Seconded, my partner somehow ended up pasting her AppleID password into Stickerclip and I couldn't figure out a way to remove it.

**Comment by icpryde** [comment]
Yes please would love to be able to delete stickers in the sticker history and maybe. Add a favourites section as well so we don’t lose the ones we like

**Comment by alcor** [comment]
Most recent version (1.1.1) now allows deletion - just swipe up to expand the sticker panel, and choose "Select" :‌)
